### ISSUE TITLE
cifar10上linear的结果超过了论文中的结果(92.0vs90.6)

### ISSUE THREAD

**Issue by xieenze** [leftthomas/SimCLR#1]
请问下是什么原因导致的呢

**Comment by leftthomas** [comment]
@xieenze not surpassing, see Figure B.5.

**Comment by xmengli** [comment]
@xieenze I guess he means Figure B.7 in the paper. The paper achieves nearly 93% with batch size 512. Maybe including the tricks can close the gap between this code and the orignal code.
