### ISSUE TITLE
Why do you modify 'conv1' and remove maxpooling from ResNet50?

### ISSUE THREAD

**Issue by AkihiroSasabe** [leftthomas/SimCLR#13]
Thanks very much for such a straightforward implementation of SimCLR.

Why do you change conv1's strides from 2 to 1 and kernel_size from 7 to 3 ,and remove maxpooling from torchvision's resnet? Does those changes contribute to  the performance? 
https://github.com/leftthomas/SimCLR/blob/cee178b6cab1efab67f8b527a0cff91c9e793f5c/model.py#L12-L16

The encoder of torchvision's resnet downsamples the feature maps for 5 times (at 'conv1', 'maxpool', 'layer2', 'layer3', 'layer4') and the size of the output will finally be 1/32 of the input image. However the encoder of your SimCLR downsamples the input for just 3 times (1/8). Are those changes done simply because you're using cifar10 with 32 pixels as a dataset? Aren't those changes appropriate for datasets with a large number of pixels, such as ImageNet?

**Comment by leftthomas** [comment]
@AkihiroSasabe just because the tested dataset is cifar10.

**Comment by AkihiroSasabe** [comment]
Thank you for the quick reply!
