### ISSUE TITLE
Contrastive loss value

### ISSUE THREAD

**Issue by abduallahmohamed** [leftthomas/SimCLR#14]
Hi, 
thanks for your work. I was wondering about the convergence value of the contrastive loss, I can see it around 4~3 while training the model but I don't know how far it will go down, any idea about this? Also are you able to share graphs or logs of the loss function for your trained model. This can be helpful in understanding the model behavior.

**Comment by leftthomas** [comment]
@abduallahmohamed  the download link has provided the log file
