### ISSUE TITLE
Batch size 1024 in V100?

### ISSUE THREAD

**Issue by FerranAlet** [leftthomas/SimCLR#16]
Hi,

Thanks for the great codebase.

I've tried training the proposed batch_size 1024 on a V100, but it runs out of memory. Am I doing something wrong or is the limit the default 512 (instead of the proposed 1024 in README)? For me the memory for 512 is 29.9, close to the limit of 32.

Thanks!

**Comment by leftthomas** [comment]
@FerranAlet the result is obtained with batch size 512, not 1024, look the table in readme
