### ISSUE TITLE
Data augmentation in linear evaluation 

### ISSUE THREAD

**Issue by fawazsammani** [leftthomas/SimCLR#20]
Hello. Nice work. Regarding the linear evaluation after pre-training (`linear.py`), I’ve noticed that you used data augmentation just like in pre-training, as you do: 

`train_data = CIFAR10(root='data', train=True, transform=utils.train_transform, download=True)`

However, the paper mentioned that they do not do any data augmentation during linear evaluation. Have you experimented without data augmentation in linear evaluation training?

**Comment by leftthomas** [comment]
@fawazsammani  you could try, I think it not influence the essence.
