### ISSUE TITLE
Calculation of Loss in train() seems wrong?

### ISSUE THREAD

**Issue by wangruoyu1126** [leftthomas/SimCLR#27]
In function train(), while calculating InfoNCE Loss, sim_matrix has the shape [2*B, 2*B-1]. However, shouldn't it be [2*B, 2*(B-1)]? 

In the given code, while doing the mask_select on line 29, it will also select one augmented positive sample, and consider it as a negative sample. So the calculation of Loss is inaccurate. Correct me if my understanding is wrong. Thanks!

**Comment by leftthomas** [comment]
@wangruoyu1126 According to my memory, the number of negative samples used in the paper is 2B-1，ref Eq. (1) in that paper.

**Comment by wangruoyu1126** [comment]
Thanks. Yes you are right, refer to Eq. (1), 2B-1 is correct.

Though it feels a bit weird that in that paper, just a few lines before Eq. (1), it says 2(N-1) are used as negative samples, and I found some other implementations use 2(N-1) in their code. And personally I feel 2(N-1) is more intuitive.

But anyways, thanks for your code and prompt reply.
