### ISSUE TITLE
Why no upscale back to original size in augmentations?

### ISSUE THREAD

**Issue by vedantroy** [leftthomas/SimCLR#29]
The SimCLR paper says:

> In this work, we sequentially apply three simple augmentations: random
> cropping followed by resize back to the original size, random color distortions, and random Gaussian blur

but it seems like the augmentations used in this repository first do a random crop, but do not afterwards resize the crop back to the original size. Why the difference? Am I misunderstanding the SimCLR paper?

I guess the original paper doesn't make a lot of sense, since resizing back to the original size would cause the images in the batch to have different sizes.

**Comment by leftthomas** [comment]
@vedantroy as mentioned in `readme`, this repo is not a strict reproduction.
