### ISSUE TITLE
Batch size doesn't affect

### ISSUE THREAD

**Issue by momendoufu** [leftthomas/SimCLR#34]
In my experiments, the evaluation accuracy get worse results when using big batch size. For example, at default setting, batch size 256 get 79.23% yet 512 get 78.38%, and it same as resnet18 and 50. I think it contray to paper's result of simclr.
Does anyone have same issue?

**Comment by leftthomas** [comment]
@momendoufu you could try different random seed and big dataset, such as ImageNet
