### ISSUE TITLE
Pretrained Model Links

### ISSUE THREAD

**Issue by abhinavagarwalla** [leftthomas/SimCLR#4]
Thank you for this amazing work.
I am struggling to download the pretrained models from Baidu disk. I tried various things such as baidu-dl extension, pandownloader, etc. none of which is working. Is it possible for you to upload to a different service like Google Drive or Dropbox? Thanks in advance.

**Comment by leftthomas** [comment]
@abhinavagarwalla sorry, my Google Driver is full, maybe you could try train it by yourself, it's fast.
