### ISSUE TITLE
Low accuracy after linear evaluation

### ISSUE THREAD

**Issue by ryancampbell514** [leftthomas/SimCLR#9]
Hello,

I ran main.py followed by linear.py using the default arguments. At the end of linear.py, my top-1 test accuracy was only able to reach 25%. Why is it that I do not achieve 92% top1 accuracy after the 100 epochs?

Thanks

**Comment by leftthomas** [comment]
@ryancampbell514 check your code, and use the arguments as paper said

**Comment by YangYang** [comment]
Do you achieve better performance on the linear evaluation stage? @ryancampbell514
